services:
  wg-easy:
    build: .
    command: npm run serve
    volumes:
      - ./src/:/app/
      # - ./data/:/etc/wireguard
    ports:
      - "51820:51820/udp"
      - "51821:51821/tcp"
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      # - PASSWORD_HASH=p
      - WG_HOST=192.168.100.3
