name: Build & Publish Latest

on:
  push:
    branches:
      - v14

jobs:
  deploy:
    name: Build & Deploy
    runs-on: ubuntu-latest
    if: |
      github.repository_owner == 'xwvike' &&
      !contains(github.event.head_commit.message, '!skipci')
    permissions:
      packages: write
      contents: read
    steps:
    - uses: actions/checkout@v4
      with:
        ref: v14

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build & Publish Docker Image
      uses: docker/build-push-action@v6
      with:
        push: true
        platforms: linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64/v8
        tags: ghcr.io/xwvike/wg-easy:latest, ghcr.io/xwvike/wg-easy:14
