name: Lint

on:
  push:
    branches:
      - v14
  pull_request:

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    if: github.repository_owner == 'xwvike'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          check-latest: true
          cache: 'npm'

      - name: npm run lint
        run: |
          cd src
          npm ci
          npm run lint
